#ifndef STDLIB_H
#define STDLIB_H

#include <stddef.h>
#include <stdint.h>

// allocate memory in 4kb blocks
void *malloc(size_t size);

// allocate memory in 4kb blocks and set content to 0
void *calloc(size_t size);

// free a pointers heap memory
void free(void *ptr);

// ascii to integer
uint32_t atoi(const char *buffer);

// return a random number between 0 and RAND_MAX
uint32_t rand(void);

// return seed generated by rand
void srand(uint32_t seed);

// return a random number between lower and upper. lower inclusive
uint32_t rand_range(uint32_t lower, uint32_t upper);

// TODO: DECIMAL, OCTAL, HEX handle negative numbers
//  integer to ascii
char *itoa(int32_t integer, char *buffer, int8_t base);
#endif // !STDLIB_H
